# -*- coding: utf-8 -*-
"""biseccion-minas.tarea.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bUSlNi8mlyemZH76a4STECi3qTmrgFPl
"""

!pip install scipy
import numpy as np
import matplotlib.pyplot as plt

def f(x):
  return x **3 + 2 * x ** 2 - x
import matplotlib.pyplot as plt
import numpy as np

x = np.linspace(-4,3,101) 
plt.plot (x, f(x))
plt.grid()
plt.show()

def f(x):
    return x **3 + 2 * x ** 2 - x

from scipy import optimize

root = optimize.bisect(f, -4, 3)
root